apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjonskalkulator-microfrontend-ssr
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  tokenx:
    enabled: true
  image: {{ image }}
  port: 3000
  liveness:
    path: /pensjonskalkulator-microfrontend-ssr/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /pensjonskalkulator-microfrontend-ssr/api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
  ingresses:
    - "https://www.intern.dev.nav.no/pensjonskalkulator-microfrontend-ssr"
    - "https://www.ansatt.dev.nav.no/pensjonskalkulator-microfrontend-ssr"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 128Mi
